### ISSUE TITLE
v3.1.0 won't open

### ISSUE THREAD

**Issue by lukasz-migas** [michaelmarty/UniDec#28]
Hi,

Just to let you know when you try to start the latest version there is an issue with the path of the preset manager. I am pretty sure you just need to change this file to handle `cwd` rather than a hard-coded path.

https://github.com/michaelmarty/UniDec/blob/38e54abc585f732e17eea305d2440ba53493f4c1/unidec_modules/isolated_packages/preset_manager.py#L8

**Comment by michaelmarty** [comment]
Thanks for catching this. It's fixed in the version online. Try it out and let me know if it works. Thanks!
