### ISSUE TITLE
Import of mzML files for "Using MetaUniDec to Analyze Chromatograms" not working

### ISSUE THREAD

**Issue by wendscheck** [michaelmarty/UniDec#39]
Hi  michaelmarty, 
I was trying to import my MS data as you nicely described in your Wiki "Using MetaUniDec to Analyze Chromatograms". My data was acquired on a Synapt G1 with MassLynx V4.1 and i converted it by using MSConvert V3 to mzML with default parameters. Then i followed your description in MetaUniDec (Version 4.1.2): File/Automated Chromatogram Parsing/Auto Import Chromatogram by Scans and used Scan step of 1.0. At this point I receive the following issue: 

UniDec Path: D:\UniDec_Windows_Dist_200121\UniDec.exe
Display Size  (1920, 1080)
TESTING: ['D:\\Daniel\\20200207_P495\\rawfiles\\SYNAPT01502.mzML']
SYNAPT01502.mzML
Reading mzML: D:\Daniel\20200207_P495\rawfiles\SYNAPT01502.mzML
'NoneType' object is not subscriptable
Errors: ['D:\\Daniel\\20200207_P495_subunitxchange\\rawfiles\\SYNAPT01502.mzML']

Any ideas? 

Thanks for your help, 
Daniel

**Comment by michaelmarty** [comment]
Hi Daniel,
Thanks for getting in touch. I've had issues before with converting Waters files into mzML. Can you send an example of the raw file and the mzML to mtmarty@email.arizona.edu? Also, does the Raw file open with UniDec? Thanks, MTM

**Comment by wendscheck** [comment]
Hi Michael, 
I just send you the files via e-mail. I can open the rawfiles in UniDec using file tab -> Open Waters Raw File. 
Best, 
Daniel

**Comment by michaelmarty** [comment]
Resolved with update to pymzml and with try/except clause on getting start time. Fix loaded in Version 4.2. Thanks!
