### ISSUE TITLE
Exporting Waterfall Plot from Meta UniDec 4.2

### ISSUE THREAD

**Issue by wendscheck** [michaelmarty/UniDec#43]
Hi, 
is there a hidden option to export the fancy Waterfall plot from MetaUniDec 4.2.0 or is it not possible up to now? 
Best, Daniel

**Comment by michaelmarty** [comment]
Hi Daniel,
Yes, you can do it by middle clicking on the plot, which opens a save figure dialog. You can set the file output type by changing the file name (.png, .pdf, etc.). You should also be able to click on the plot and then click Ctrl+C to copy/paste it as an image into another program. Check out this Wiki article for some other hidden features: https://github.com/michaelmarty/UniDec/wiki/Hidden-Features. 
Let me know if that works! Thanks, MTM

**Comment by wendscheck** [comment]
Hi Michael, 
i read your Wiki yesterday and tried all your nicely described ways for exporting several times but no one worked out. I tried it now again and it worked - somewhat embarrassing. Sorry for bothering you and thank you again!  ; )
