### ISSUE TITLE
RNA or DNA deconvolution 

### ISSUE THREAD

**Issue by lin20181220** [michaelmarty/UniDec#47]
Can I do RNA MS spectrum deconvolution and how to change the settings?

**Comment by michaelmarty** [comment]
Hey! Yes, you can. It should not care what sorts of analytes you are studying, but you may need to adjust the default settings to improve the deconvolution. For example, you may need to switch to negative mode if you are using that. Check out the videos in the wiki: https://github.com/michaelmarty/UniDec/wiki, and feel free to email me if you have more questions or want some advice on some example spectra.
