### ISSUE TITLE
Scale problem

### ISSUE THREAD

**Issue by AlexanderMoysa** [michaelmarty/UniDec#49]
Dear colleagues, 
Could you help me with the scale? 
In the plot of deconvoluted mass spectra, the upper side is a little bit cut.
Please see the attached figure.
Is it possible to overcome this problem? 

Best,
Alexander
![1](https://user-images.githubusercontent.com/26464268/102470782-b00cee00-4054-11eb-920e-17f2ed289787.jpg)

**Comment by michaelmarty** [comment]
Thanks, Alexander. I've got it on my list to work on. I've had trouble figuring out how to fix this without getting other artifacts to pop up on the sides when you zoom. There is likely a solution in the ZoomBox.py file for anyone interested in helping on this. But, in the mean time, you can work around this by saving the file as a PDF and using Illustrator or another vector graphics editor to remove or extend the box around the plot manually for publications.

**Comment by michaelmarty** [comment]
Ok, I think I've finally got this fixed. It consumed more hours of my life than I'd like to admit. Look for the fix in the next version.
