### ISSUE TITLE
Suggestion for MetaUniDec to skip bad runs

### ISSUE THREAD

**Issue by mzhou2012** [michaelmarty/UniDec#55]
Hi Michael,
I have a suggestion for MetaUniDec to skip "bad" runs.
In batch runs some bad runs may have nearly no signal (just noise), when UniDec goes through the data in HDF5, a bad run will cause it to stop processing further. I also can't find good place to edit HDF5 directly. The only way I found is to recreate HDF5 file without the bad runs. Retyping the variables can be tedious.
Another small suggestion is to export file names/variables in the txt output in UniDec.

Thanks,
Mowei

**Comment by michaelmarty** [comment]
Hey Mowei!
I think you can do this by right clicking on the list of spectra on the left and deleting individual spectra, which will also delete them from the HDF5 file. Give that a try and see if it does what you are hoping. Thanks!
MTM

**Comment by michaelmarty** [comment]
Hi Mowei,
Ok, after a long time, I think I finally fixed this. It should be much more error tolerant in version 5.1.0. Stay tuned for the release or email me if you want a sneak peak. Thanks,
MTM
