### ISSUE TITLE
Unable to output the DScore for each deconvoluted mass

### ISSUE THREAD

**Issue by Dondonn** [michaelmarty/UniDec#84]
I couldn't find a way to get the DScore for each deconvoluted mass from UniDec. 
The _error.txt file contains only the Uniscore but not the DScore; is there a function, parameter, or way to output the DScore for each deconvoluted mass? Or is it the second column in the _mass.txt file? (Probably not)

Hope someone can help with this issue. Thanks!

![image](https://github.com/michaelmarty/UniDec/assets/48869711/52f043c6-12b1-458a-956a-740fb75a6de2)
![image](https://github.com/michaelmarty/UniDec/assets/48869711/2aaf62bd-d3a9-4dc2-bd00-682c7fb626d5)

**Comment by michaelmarty** [comment]
Ok, it's fixed for the next version. When it gets posted, you can uses "Analysis > Export Peaks Parameters and Data" to export a peakparams.dat file with it in it. Until then, you can use the copy all trick from the comment above. Thanks!
