### ISSUE TITLE
mzML files won't open - error 

### ISSUE THREAD

**Issue by mcyr345** [michaelmarty/UniDec#90]
I just downloaded UniDec and when I try to open a mzML file, I'm getting a Unicode error. 

![image](https://github.com/michaelmarty/UniDec/assets/149815059/4d436a07-f23f-4a62-b15d-54b2047dc95a)

**Comment by michaelmarty** [comment]
Hey! I'm not seeing this error with opening mzML files on my end. It could be an issue with the particular file. Would you mind trying this file? [myo.zip](https://github.com/michaelmarty/UniDec/files/13313255/myo.zip)

If that one works, then it might be your mzML conversion settings. Thanks!
